---
# -----------------------------------------------------------------------------
# docker-compose installation
# -----------------------------------------------------------------------------
- name: install docker compose
  become: true
  become_method: sudo
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
    owner: root
    group: root
    force: true

