---
# -----------------------------------------------------------------------------
# docker-engine installation
# -----------------------------------------------------------------------------
- name: setup repository for docker engine installation
  become: true
  become_method: sudo
  apt:
    package: "{{ item }}"
    state: present
    force: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-setuptools

- name: install pip the safe way
  become: true
  become_method: sudo
  easy_install:
    name: pip
    state: present

- name: ensure docker python lib is present
  become: true
  become_method: sudo
  pip:
    name: docker
    state: latest

- name: add docker official GPG key
  become: true
  apt_key:
    url: "{{ docker_apt_url }}/gpg"
    state: present

- name: add apt repository
  become: true
  become_method: sudo
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_apt_url }} {{ ansible_distribution_release }} {{ docker_repo }}"
    state: present
    filename: docker
    update_cache: true

- name: ensure there was no previous Docker Engine installed
  become: true
  apt:
    package: "{{ item }}"
    state: absent
    purge: true
  with_items:
    - docker
    - docker-engine

- name: install latest docker engine
  become: true
  become_method: sudo
  apt:
    package: docker-ce
    state: latest
    update_cache: true
    cache_valid_time: 3600
    force: true

- name: add user to docker group
  become: true
  become_method: sudo
  user:
    append: true
    group: docker
    name: "{{ ansible_user_id }}"
    state: present
  notify: restart docker

- name: trigger Docker Restart handler
  meta: flush_handlers

